version: "3.9"

services:
  orchestrator:
    build: .
    container_name: veltrix-orchestrator
    ports:
      - "3000:3000" # Runs app.js
      - "4000:4000" # Runs api.js
    env_file:
      - .env
    volumes:
      - .:/app
      - ./logs:/app/logs
    restart: unless-stopped
