---
name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      IMAGE_NAME: veltrix-orchestrator
      REGISTRY: ghcr.io/abhishekkole

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/abhishekkole/veltrix-orchestrator:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/abhishekkole/veltrix-orchestrator:${{ github.sha }}

      - name: Output image URL
        run: |
          echo "Image pushed:ghcr.io/abhishekkole/veltrix-orchestrator:${{ github.sha }}"